### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by huangju1** [albertwy/SWRM#3]
作者您好！
按照您那上面的步骤，运行后出现这样的报错TypeError: 'bool' object is not callable
File "G:\NLP训练\SSSSSSSS\SWRM-main\trains\singleTask\SWRM.py", line 145, in do_train
    for batch_data in td:
![image](https://user-images.githubusercontent.com/55517780/175202966-2c5c1e57-d82c-4f40-b691-c84e3bedf24c.png)
经排查后是这块代码
![image](https://user-images.githubusercontent.com/55517780/175203111-d1ec70f8-faed-45bd-a377-5e388c5ec9dc.png)
希望得到您的回复！

**Comment by albertwy** [comment]
你好，看起来是某个变量是bool类型，但是被当成函数调用了，目前信息没办法确定哪里出问题了。可以把上下文的变量print一下么，看看中间变量td,batch_data类型。

**Comment by albertwy** [comment]
This problem is solved. 

Problem:
![image](https://user-images.githubusercontent.com/17995697/175915716-aa1abab2-235d-4f90-908a-e9c330ccbb7e.png)


Solution:
- Set the **num_workers** to **0** (It's ok as the dataset is small.)

Similar Issues
- [Error while Multiprocessing in Dataloader](https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845)
- [DataLoader error due to multiprocessing](https://discuss.pytorch.org/t/dataloader-error-due-to-multiprocessing/41291)
