### ISSUE TITLE
Can I ask what this means？

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [albertwy/SWRM#4]
When I run run.py like python run.py --modelName swrm --expSetting gold_asr_train, result like this :
<img width="984" alt="image" src="https://user-images.githubusercontent.com/72587415/198874907-1369128e-3650-4a93-9f18-b32da58b12b5.png">
I want to know what this corresponds to that part of your paper, what does it mean？ and what is its output mean? Could you tell me, Please?

**Comment by YUZHIWANG-bug** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/72587415/198875371-c1a32f02-0bfc-46be-87ca-48f4d6e44754.png">

**Comment by albertwy** [comment]
Hi, just ignore it. It means that using the pre-trained BERT model to encode the textual input. Some weights for the pre-trained task are not used and we only use the transformer encoder.   The progress bar shows the training/validation progress. Because there are many epochs, the progress bar will show many times. When the training is finished, you can obtain the results in the "results" directory.

**Comment by YUZHIWANG-bug** [comment]
> Hi, just ignore it. It means that using the pre-trained BERT model to encode the textual input. Some weights for the pre-trained task are not used and we only use the transformer encoder. The progress bar shows the training/validation progress. Because there are many epochs, the progress bar will show many times. When the training is finished, you can obtain the results in the "results" directory.

I think I may know, thank you very much for your reply, and look forward to the next communication with you.
